apiVersion: 1
groups:
    - orgId: 1
      name: job alert
      folder: bert
      interval: 1m
      rules:
        - uid: dej6cljqgxekge
          title: Alert max jobs
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cej41rlo2r11cd
              model:
                disableTextWrap: false
                editorMode: builder
                expr: prediction_status{model="bert"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: Task is up to 5 jobs
            summary: Alert Sentiment analysis
          isPaused: false
          notification_settings:
            receiver: admin-email
