services:
  backend:
    build: .
    container_name: sentimental_analyses_backend
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./mlruns:/app/mlruns/
      - ./src:/app/src/
    # stdin_open: true
    # tty: true
    entrypoint: "./entrypoint.sh"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5001
      - HOST_DEPLOY=0.0.0.0

  prometheus:
    image: prom/prometheus:latest
    container_name: sentimental_analyses_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: sentimental_analyses_grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/tweet_dashboards.yaml
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/tweet_dashboard.json
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=shift.python.software@gmail.com
      - GF_SMTP_PASSWORD=meph potg kjia pfah
      - GF_SMTP_FROM_ADDRESS=shift.python.software@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    container_name: sentimental_analyses_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  db:
    image: mongo:4.4
    container_name: sentimental_analyses_db
    ports:
      - "27017:27017"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: sentimental_analyses_promtail
    volumes:
      - ./log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped
  # nginx:
  #   image: nginx
  #   container_name: sentimental_analyses_nginx
  #   ports:
  #     - "81:80"
  #     - '444:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend

volumes:
  grafana-storage:
