services:
  backend:
    build: .
    container_name: sentimental_analyses_backend
    ports:
      - "5000:5000"
      -  "5001:5001"
    volumes:
      - ./mlflow:/app/mlruns/
    entrypoint: "./entrypoint.sh"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5001
      - HOST_DEPLOY = 0.0.0.0

  nginx:
    image: nginx
    container_name: sentimental_analyses_nginx
    ports:
      - "80:80"
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend