apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ds_prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: ds_loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: true